### ISSUE TITLE
Password returned in plain text on /signup error

### ISSUE THREAD

**Issue by leodonny** [weareopensource/Node#147]
**Describe the bug**
When you don't match the regex check on the route `/signup` Node server returned you an error with your password in plain-text.
I'm using the Angular stack.

**To Reproduce**
Use this route `/api/auth/signup` with `POST` and an object which don't match the required schema:

```
{
  email: "test@gmail.com"
  firstName: "Léo"
  lastName: "qwerty"
  password: "H7v8r9:=T"
  username: "Léoqwerty"
}
```

The returned object will be:

```
{  
  "type":"error",
  "message":"schema validation error",
  "error":{  
    "original":{  
      "firstName":"Léo",
      "lastName":"qwerty",
      "email":"test@gmail.com",
      "password":"H7v8r9:=T",
      "username":"Léoqwerty"
    },
    "details":[  
      {  
        "message":"username with value léoqwerty fails to match the required pattern: /^(?=[\\w.-]+$)(?!.*[._-]{2})(?!\\.)(?!.*\\.$).{3,34}$/",
        "type":"string.regex.base"
      }
    ]
  }
}
```

**Expected behavior**
If Node returns the password, it has to be encrypted.

**Screenshots**
<img width="1640" alt="Capture d’écran 2019-04-10 à 14 21 06" src="https://user-images.githubusercontent.com/10722479/55878091-077a6b80-5b9c-11e9-9ed9-38c4e5773e2e.png">

**Comment by PierreBrisorgueil** [comment]
Hello, thx for this :) 

it's the classic operation today, there are several discussions about it : https://stackoverflow.com/questions/962187/plain-text-password-over-https

However, even if the data is in plain text, it is not the role of the server to return sensitive data. 
As we filter the returned data by deleting the sensitive fields in the good queries, we have to do it for errors, and schema errors 

I make a PR asap 👍

**Comment by leodonny** [comment]
Oh! I understand. Thank you for fixing this :)
