### ISSUE TITLE
ENOENT: no such file or directory, lstat error running test cases

### ISSUE THREAD

**Issue by jpegram2** [weareopensource/Node#96]
Tinkering with your code and I ran into an issue where 'as is' all the test run successfully. However, there is a validation check:  
console.log config/index.js:75
    + Important warning: config.domain is empty. It should be set to the fully qualified domain of the app.

when I set a FQDN in the config/defaults/development.js file for domain:
  domain: 'sitename.domain.com',
 I get the follow errors running the Logger Configuration.

>       Testing Logger Configuration
        ✓ should verify that a file logger object was created using the logger configuration (9ms)
        ✕ should not create a file transport object if critical options are missing: filename (3ms)
        ✕ should not create a file transport object if critical options are missing: directory (1ms)

  ● Core Server Config: › Configuration Tests: › Testing Logger Configuration › should not create a file transport object if critical options are missing: filename

    ENOENT: no such file or directory, lstat '/Users/jpegram2/Sites/node/api.macoutpost.site/node_modules/jest-util/node_modules/slash'

      at _slash (node_modules/jest-util/build/getConsoleOutput.js:29:39)

  ● Core Server Config: › Configuration Tests: › Testing Logger Configuration › should not create a file transport object if critical options are missing: directory

    ENOENT: no such file or directory, lstat '/Users/jpegram2/Sites/node/api.macoutpost.site/node_modules/jest-util/node_modules/slash'

      at _slash (node_modules/jest-util/build/getConsoleOutput.js:29:39)

> 

Any thoughts?

**Comment by PierreBrisorgueil** [comment]
hello @jpegram2 
Thanks for this feedback. 
I'm getting closer to something clean but the work is still in beta, no release for the moment, but it should happen quickly :).

This is linked to https://github.com/tschaub/mock-fs/issues/234

I have a fix but I'm just taking a little time to dig up the subject

**Comment by jpegram2** [comment]
@PierreBrisorgueil I don't suppose you have that fix in a branch or something do you?

**Comment by PierreBrisorgueil** [comment]
it's an issue at mock-fs that we don't actually use, it was just initialized from Riess (@lirantal), I have not yet looked for why. I have disabled for the moment the time to see if we put it back in place. 

Available on the master ;)
